// This file is automatically generated. Do not edit it directly.
export const supabase = {
  from: () => {
    throw new Error('Supabase has been removed. This page must be updated to use the PHP API.');
  },
  auth: {
    signInWithPassword: async () => {
      throw new Error('Supabase has been removed. Use PHP API auth instead.');
    },
    signUp: async () => {
      throw new Error('Supabase has been removed. Use PHP API user creation instead.');
    },
    signOut: async () => {
      throw new Error('Supabase has been removed. Use PHP API logout instead.');
    },
    getSession: async () => {
      throw new Error('Supabase has been removed. Use PHP API session instead.');
    },
    onAuthStateChange: () => {
      throw new Error('Supabase has been removed. Use PHP API session instead.');
    },
  },
} as any;